"""initial_schema

Revision ID: 73b2713c876c
Revises: 
Create Date: 2026-04-26 21:00:22.393440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b2713c876c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cl_ord_id', sa.String(length=64), nullable=False, comment='FIX tag 11'),
    sa.Column('symbol', sa.String(length=32), nullable=False, comment='FIX tag 55'),
    sa.Column('side', sa.String(length=4), nullable=False, comment='FIX tag 54 (1=Buy, 2=Sell)'),
    sa.Column('msg_type', sa.String(length=16), nullable=False, comment='Human-readable msg type'),
    sa.Column('order_qty', sa.DECIMAL(precision=18, scale=6), nullable=True, comment='FIX tag 38'),
    sa.Column('price', sa.DECIMAL(precision=18, scale=6), nullable=True, comment='FIX tag 44'),
    sa.Column('fill_price', sa.DECIMAL(precision=18, scale=6), nullable=True, comment='Execution fill price'),
    sa.Column('status', sa.String(length=32), nullable=True, comment='FIX tag 39 OrdStatus'),
    sa.Column('seq_num', sa.Integer(), nullable=True, comment='FIX tag 34'),
    sa.Column('sender_comp_id', sa.String(length=64), nullable=True, comment='FIX tag 49'),
    sa.Column('target_comp_id', sa.String(length=64), nullable=True, comment='FIX tag 56'),
    sa.Column('raw_fix', sa.Text(), nullable=False, comment='Original FIX message verbatim'),
    sa.Column('received_at', sa.DateTime(), nullable=False, comment='Timestamp when record was persisted'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_cl_ord_id', 'orders', ['cl_ord_id'], unique=False)
    op.create_index('ix_orders_msg_type', 'orders', ['msg_type'], unique=False)
    op.create_index('ix_orders_received_at', 'orders', ['received_at'], unique=False)
    op.create_index('ix_orders_symbol', 'orders', ['symbol'], unique=False)
    op.create_index('ix_orders_symbol_received', 'orders', ['symbol', 'received_at'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=64), nullable=False, comment='e.g. DUPLICATE, PRICE_SPIKE'),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_fix', sa.Text(), nullable=True, comment='Relevant FIX snippet'),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anomalies_detected_at', 'anomalies', ['detected_at'], unique=False)
    op.create_index('ix_anomalies_order_id', 'anomalies', ['order_id'], unique=False)
    op.create_index('ix_anomalies_type', 'anomalies', ['anomaly_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_anomalies_type', table_name='anomalies')
    op.drop_index('ix_anomalies_order_id', table_name='anomalies')
    op.drop_index('ix_anomalies_detected_at', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index('ix_orders_symbol_received', table_name='orders')
    op.drop_index('ix_orders_symbol', table_name='orders')
    op.drop_index('ix_orders_received_at', table_name='orders')
    op.drop_index('ix_orders_msg_type', table_name='orders')
    op.drop_index('ix_orders_cl_ord_id', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
